### ISSUE TITLE
Can't run sample

### ISSUE THREAD

**Issue by edtsech** [liquidz/misaki#9] opened 2012-05-19 13:03 UTC
Clojure 1.4.0
Leiningen 1.7.1 on Java 1.6.0_31 Java HotSpot(TM) 64-Bit Server VM
All tests pass.

```
java.lang.RuntimeException: Unable to resolve symbol: css in this context, compiling:(NO_SOURCE_PATH:1) * compiling all templates: ... FAIL

    at clojure.lang.Compiler.analyze(Compiler.java:6281)
    at clojure.lang.Compiler.analyze(Compiler.java:6223)
    at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3497)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:6457)
    at clojure.lang.Compiler.analyze(Compiler.java:6262)
    at clojure.lang.Compiler.analyze(Compiler.java:6223)
    at clojure.lang.Compiler$VectorExpr.parse(Compiler.java:2954)
    at clojure.lang.Compiler.analyze(Compiler.java:6264)
    at clojure.lang.Compiler.analyze(Compiler.java:6223)
    at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3548)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:6457)
    at clojure.lang.Compiler.analyze(Compiler.java:6262)
    at clojure.lang.Compiler.analyze(Compiler.java:6223)
    at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:5618)
    at clojure.lang.Compiler$LetExpr$Parser.parse(Compiler.java:5919)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:6455)
    at clojure.lang.Compiler.analyze(Compiler.java:6262)
    at clojure.lang.C * compiling all tags: ... FAIL
ompiler.analyzeSeq(Compiler.java:6443)
    at clojure.lang.Compiler.analyze(Compiler.java:6262)
    at clojure.lang.Compiler.analyze(Compiler.java:6223)
    at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:5618)
    at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5054)
    at clojure.lang.Compiler$FnExpr.parse(Compiler.java:3674)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:6453)
    at clojure.lang.Compiler.analyze(Compiler.java:6262)
    at clojure.lang.Compiler.analyze(Compiler.java:6223)
    at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:5618)
    at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5054)
    at clojure.lang.Compiler$FnExpr.parse(Compiler.java:3674)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:6453)
    at clojure.lang.Compiler.analyze(Compiler.java:6262)
    at clojure.lang.Compiler.eval(Compiler.java:6508)
    at clojure.lang.Compiler.eval(Compiler.java:6501)
    at clojure.lang.Compiler.eval(Compiler.java:6477)
    at clojure.core$eval.invoke(core.clj:2797)
    at misaki.transform$transform$fn__56.invoke(transform.clj:54)
    at clojure.lang.ArrayChunk.reduce(ArrayChunk.java:60)
    at clojure.core.protocols$fn__5890.invoke(protocols.clj:94)
    at clojure.core.protocols$fn__5854$G__5849__5863.invoke(protocols.clj:19)
    at clojure.core.protocols$seq_reduce.invoke(protocols.clj:31)
    at clojure.core.protocols$fn__5873.invoke(protocols.clj:60)
    at clojure.core.protocols$fn__5828$G__5823__5841.invoke(protocols.clj:13)
    at clojure.core$reduce.invoke(core.clj:6030)
    at misaki.transform$transform.invoke(transform.clj:54)
    at misaki.template$load_template.invoke(template.clj:64)
    at misaki.template$load_template.invoke(template.clj:47)
    at misaki.template$load_template.invoke(template.clj:55)
    at misaki.template$load_template.invoke(template.clj:47)
    at misaki.template$load_template.invoke(template.clj:55)
    at misaki.core$generate_html.doInvoke(core.clj:92)
    at clojure.lang.RestFn.invoke(RestFn.java:410)
    at misaki.core$compile_template.invoke(core.clj:147)
    at misaki.core$compile_all_templates$fn__687.invoke(core.clj:169)
    at clojure.core$every_QMARK_.invoke(core.clj:2370)
    at misaki.core$compile_all_templates.invoke(core.clj:170)
    at misaki.server$do_all_compile.invoke(server.clj:27)
    at misaki.server$start_watcher.invoke(server.clj:60)
    at misaki.server$_main.doInvoke(server.clj:79)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.lang.Var.invoke(Var.java:415)
    at user$eval29.invoke(NO_SOURCE_FILE:1)
    at clojure.lang.Compiler.eval(Compiler.java:6511)
    at clojure.lang.Compiler.eval(Compiler.java:6501)
    at clojure.lang.Compiler.eval(Compiler.java:6477)
    at clojure.core$eval.invoke(core.clj:2797)
    at clojure.main$eval_opt.invoke(main.clj:297)
    at clojure.main$initialize.invoke(main.clj:316)
    at clojure.main$null_opt.invoke(main.clj:349)
    at clojure.main$main.doInvoke(main.clj:427)
    at clojure.lang.RestFn.invoke(RestFn.java:421)
    at clojure.lang.Var.invoke(Var.java:419)
    at clojure.lang.AFn.applyToHelper(AFn.java:163)
    at clojure.lang.Var.applyTo(Var.java:532)
    at clojure.main.main(main.java:37)
Caused by: java.lang.RuntimeException: Unable to resolve symbol: css in this context
    at clojure.lang.Util.runtimeException(Util.java:170)
    at clojure.lang.Compiler.resolveIn(Compiler.java:6766)
    at clojure.lang.Compiler.resolve(Compiler.java:6710)
    at clojure.lang.Compiler.analyzeSymbol(Compiler.java:6671)
    at clojure.lang.Compiler.analyze(Compiler.java:6244)
    ... 73 more
java.lang.RuntimeException: Unable to resolve symbol: css in this context, compiling:(NO_SOURCE_PATH:1)
    at clojure.lang.Compiler.analyze(Compiler.java:6281)
    at clojure.lang.Compiler.analyze(Compiler.java:6223)
    at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3497)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:6457)
    at clojure.lang.Compiler.analyze(Compiler.java:6262)
    at clojure.lang.Compiler.analyze(Compiler.java:6223)
    at clojure.lang.Compiler$VectorExpr.parse(Compiler.java:2954)
    at clojure.lang.Compiler.analyze(Compiler.java:6264)
    at clojure.lang.Compiler.analyze(Compiler.java:6223)
    at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3548)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:6457)
    at clojure.lang.Compiler.analyze(Compiler.java:6262)
    at clojure.lang.Compiler.analyze(Compiler.java:6223)
    at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:5618)
    at clojure.lang.Compiler$LetExpr$Parser.parse(Compiler.java:5919)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:6455)
    at clojure.lang.Compiler.analyze(Compiler.java:6262)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:6443)
    at clojure.lang.Compiler.analyze(Compiler.java:6262)
    at clojure.lang.Compiler.analyze(Compiler.java:6223)
    at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:5618)
    at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5054)
    at clojure.lang.Compiler$FnExpr.parse(Compiler.java:3674)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:6453)
    at clojure.lang.Compiler.analyze(Compiler.java:6262)
    at clojure.lang.Compiler.analyze(Compiler.java:6223)
    at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:5618)
    at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5054)
    at clojure.lang.Compiler$FnExpr.parse(Compiler.java:3674)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:6453)
    at clojure.lang.Compiler.analyze(Compiler.java:6262)
    at clojure.lang.Compiler.eval(Compiler.java:6508)
    at clojure.lang.Compiler.eval(Compiler.java:6501)
    at clojure.lang.Compiler.eval(Compiler.java:6477)
    at clojure.core$eval.invoke(core.clj:2797)
    at misaki.transform$transform$fn__56.invoke(transform.clj:54)
    at clojure.lang.ArrayChunk.reduce(ArrayChunk.java:60)
    at clojure.core.protocols$fn__5890.invoke(protocols.clj:94)
    at clojure.core.protocols$fn__5854$G__5849__5863.invoke(protocols.clj:19)
    at clojure.core.protocols$seq_reduce.invoke(protocols.clj:31)
    at clojure.core.protocols$fn__5873.invoke(protocols.clj:60)
    at clojure.core.protocols$fn__5828$G__5823__5841.invoke(protocols.clj:13)
    at clojure.core$reduce.invoke(core.clj:6030)
    at misaki.transform$transform.invoke(transform.clj:54)
    at misaki.template$load_template.invoke(template.clj:64)
    at misaki.template$load_template.invoke(template.clj:47)
    at misaki.template$load_template.invoke(template.clj:55)
    at misaki.template$load_template.invoke(template.clj:47)
    at misaki.core$generate_tag_html.invoke(core.clj:105)
    at misaki.core$compile_tag.invoke(core.clj:137)
    at misaki.core$compile_all_tags$fn__682.invoke(core.clj:155)
    at clojure.core$every_QMARK_.invoke(core.clj:2370)
    at misaki.core$compile_all_tags.invoke(core.clj:155)
    at misaki.server$do_all_compile.invoke(server.clj:29)
    at misaki.server$start_watcher.invoke(server.clj:60)
    at misaki.server$_main.doInvoke(server.clj:79)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.lang.Var.invoke(Var.java:415)
    at user$eval29.invoke(NO_SOURCE_FILE:1)
    at clojure.lang.Compiler.eval(Compiler.java:6511)
    at clojure.lang.Compiler.eval(Compiler.java:6501)
    at clojure.lang.Compiler.eval(Compiler.java:6477)
    at clojure.core$eval.invoke(core.clj:2797)
    at clojure.main$eval_opt.invoke(main.clj:297)
    at clojure.main$initialize.invoke(main.clj:316)
    at clojure.main$null_opt.invoke(main.clj:349)
    at clojure.main$main.doInvoke(main.clj:427)
    at clojure.lang.RestFn.invoke(RestFn.java:421)
    at clojure.lang.Var.invoke(Var.java:419)
    at clojure.lang.AFn.applyToHelper(AFn.java:163)
    at clojure.lang.Var.applyTo(Var.java:532)
    at clojure.main.main(main.java:37)
Caused by: java.lang.RuntimeException: Unable to resolve symbol: css in this context
    at clojure.lang.Util.runtimeException(Util.java:170)
    at clojure.lang.Compiler.resolveIn(Compiler.java:6766)
    at clojure.lang.Compiler.resolve(Compiler.java:6710)
    at clojure.lang.Compiler.analyzeSymbol(Compiler.java:6671)
    at clojure.lang.Compiler.analyze(Compiler.java:6244)
    ... 71 more
2012-05-19 15:01:38.271:INFO::Logging to STDERR via org.mortbay.log.StdErrLog
2012-05-19 15:01:38.283:INFO::jetty-6.1.25
2012-05-19 15:01:38.331:INFO::Started SocketConnector@0.0.0.0:8080
```

**Comment by edtsech** [comment] 2012-05-29 20:51
I think problem in this commit https://github.com/liquidz/misaki/commit/d80d9758575390043efb45f59327ac58d4ba9499
with requiring misaki.html.core, possibly here https://github.com/liquidz/misaki/commit/d80d9758575390043efb45f59327ac58d4ba9499#L5R25 .

**Comment by liquidz** [comment] 2012-06-09 01:20
The issue is confirmed with MacBook Air:

> $ java -version
> java version "1.6.0_31"
> Java(TM) SE Runtime Environment (build 1.6.0_31-b04-415-11E53)
> Java HotSpot(TM) 64-Bit Server VM (build 20.6-b01-415, mixed mode)

I fixed `use` position in transform.clj, and checked with MacBook Air(java 1.6.0_31) and Ubuntu11.10(1.6.0_24).
Would you try **bugfix** branch?

**Comment by edtsech** [comment] 2012-06-11 15:31
It works!

**Comment by liquidz** [comment] 2012-06-11 16:07
Thanks! I merged to **master** branch.

**Closed as completed** 2012-06-11 16:07 UTC
Labels: bug
